version: 2.1
orbs:
  python: skillup/python@4.0.0
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.4

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      
      - python/venv

      - run:
          name: install dependencies
          command: |
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      
      - run:
          name: typecheck
          command: |
            . venv/bin/activate
            mypy --namespace-packages --strict --implicit-reexport bankroll/
            mypy --namespace-packages --strict --implicit-reexport -p tests

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest -v

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - run:
          name: linting
          command: |
            . venv/bin/activate
            black --check bankroll tests
      
      - run:
          name: typecheck without pandas
          command: |
            . venv/bin/activate
            pip uninstall -y pandas
            mypy --namespace-packages --strict --implicit-reexport bankroll/
      
      - run:
          name: test installing
          command: |
            python3 -m venv --clear venv
            . venv/bin/activate
            pip install .